print('Hello, type your name:')
n=str(input())
print("Hello",n)
print("which place do you live?")
p=str(input())
print('hello',n, 'How is weather in',p,"?")
r=str(input())
print("hey nice to know that weather is",r)
print("what is your age")
age=int(input())
print("good to know that your age is", age, "years old")